server:
  port: 8081

app:
  backend:
    url: ${BACKEND_URL:http://backend:8080/eventos/sync}

  kafka:
    consumer:
      group-id: grupo-id-drube-tadeo
    topic: eventos-actualizacion

  jwt:
    secret: ${JWT_SECRET:secreto}
    expiration: ${JWT_EXPIRATION:60000}

spring:
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}

  kafka:
    bootstrap-servers: ${KAFKA_URL:}

    consumer:
      group-id: grupo-id-drube-tadeo
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer